# Generated by Django 3.0.3 on 2020-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200225_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='mealDirections',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mealIngredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealDirection1',
            field=models.TextField(blank=True, max_length=500, verbose_name='Direction #1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealDirection2',
            field=models.TextField(blank=True, max_length=500, verbose_name='Direction #2'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealDirection3',
            field=models.TextField(blank=True, max_length=500, verbose_name='Direction #3'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealDirection4',
            field=models.TextField(blank=True, max_length=500, verbose_name='Direction #4'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealDirection5',
            field=models.TextField(blank=True, max_length=500, verbose_name='Direction #5'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient10',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #10'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #2'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #3'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #4'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #5'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient6',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #6'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient7',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #7'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient8',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #8'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIngredient9',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ingredient #9'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealPic',
            field=models.ImageField(upload_to='images', verbose_name='Meal Image'),
        ),
    ]
