# Generated by Django 3.0.2 on 2020-02-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200226_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mealPic',
            field=models.ImageField(upload_to='', verbose_name='Meal Image'),
        ),
    ]
