# Generated by Django 3.0.2 on 2020-02-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200226_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mealDbRating',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Meal rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='mealIP',
            field=models.CharField(blank=True, max_length=16, verbose_name='IP address'),
        ),
    ]
