# Generated by Django 3.0.2 on 2020-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200228_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='mealRate',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealCalories',
            field=models.PositiveIntegerField(default=1, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealCookTime',
            field=models.PositiveIntegerField(default=1, verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealDbRating',
            field=models.PositiveIntegerField(default=1, verbose_name='Meal rating'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealIP',
            field=models.CharField(blank=True, max_length=16, verbose_name='user IP address'),
        ),
    ]
